sudo: required
services:
  - docker
before_install:
  - docker build -t docker-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true docker-client npm run test

after_success:
  - docker build -t zencles/multi-client ./client
  - docker build -t zencles/multi-nginx ./nginx
  - docker build -t zencles/multi-server ./server
  - docker build -t zencles/multi-worker ./worker
  # Log in the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push zencles/multi-client
  - docker push zencles/multi-nginx
  - docker push zencles/multi-server
  - docker push zencles/multi-worker